# Generated by Django 4.2.8 on 2023-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yt_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thumbnail', models.ImageField(upload_to='pics')),
                ('video_time', models.TimeField()),
                ('channel_pic', models.ImageField(upload_to='pics')),
                ('video_title', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('views', models.FloatField()),
                ('days', models.IntegerField()),
            ],
        ),
    ]
